spring.application.name=adpilot

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/adpilot
spring.datasource.username=adpilot
spring.datasource.password=adpilot123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

# Meta API
meta.app.id=2180813926051072
meta.app.secret=b753d69e1ca42fa8cf16327d8b5352ec
meta.redirect.uri=http://localhost:8080/api/meta/callback